using Godot.Collections;

namespace HydraTextClient.Scripts.Discord;

public static class DRPC_GTT
{
    public static Dictionary<string, string> GameToTitle = new()
    {
        ["A Difficult Game About Climbing"] = "A Difficult Game About Climbing", ["A Hat in Time"] = "A Hat in Time",
        ["A Link Between Worlds"] = "The Legend of Zelda: A Link Between Worlds",
        ["A Link to the Past"] = "The Legend of Zelda: A Link to the Past", ["A Short Hike"] = "A Short Hike",
        ["ANIMAL WELL"] = "ANIMAL WELL", ["Actraiser"] = "ActRaiser", ["Adventure"] = "Adventure",
        ["Against the Storm"] = "Against the Storm", ["Air Delivery"] = "Air Delivery",
        ["An Untitled Story"] = "An Untitled Story", ["Anodyne"] = "Anodyne",
        ["Another Crabs Treasure"] = "Another Crab's Treasure", ["Ape Escape 3"] = "Ape Escape 3",
        ["Ape Escape"] = "Ape Escape", ["Aquaria"] = "Aquaria", ["Astalon"] = "Astalon: Tears of the Earth",
        ["Balatro"] = "Balatro", ["Baldur's Gate 3"] = "Baldur's Gate 3", ["Banjo-Tooie"] = "Banjo-Tooie",
        ["Battle for Bikini Bottom"] = "SpongeBob SquarePants: Battle for Bikini Bottom",
        ["Blasphemous 2"] = "Blasphemous 2", ["Blasphemous"] = "Blasphemous", ["Bloons TD6"] = "Bloons TD 6",
        ["Bomb Rush Cyberfunk"] = "Bomb Rush Cyberfunk", ["Bomberman 64"] = "Bomberman 64",
        ["Bomberman Hero"] = "Bomberman Hero", ["Bomberman Quest"] = "Bomberman Quest",
        ["Bomberman The Second Attack"] = "Bomberman 64: The Second Attack!", ["Borderlands 2"] = "Borderlands 2",
        ["Brotato"] = "Brotato", ["Buckshot Roulette"] = "Buckshot Roulette", ["Cassette Beasts"] = "Cassette Beasts",
        ["Castlevania - Circle of the Moon"] = "Castlevania: Circle of the Moon",
        ["Castlevania - Harmony of Dissonance"] = "Castlevania: Harmony of Dissonance",
        ["Castlevania 64"] = "Castlevania 64", ["Castlevania: Dawn of Sorrow"] = "Castlevania: Dawn of Sorrow",
        ["Cat Quest"] = "Cat Quest", ["Cave Story"] = "Cave Story", ["Cavern of Dreams"] = "Cavern of Dreams",
        ["Celeste (Open World)"] = "Celeste", ["Celeste 64"] = "Celeste 64", ["Celeste"] = "Celeste",
        ["Choo-Choo Charles"] = "Choo-Choo Charles", ["Chrono Trigger Jets of Time"] = "Chrono Trigger",
        ["Civilization V"] = "Sid Meier's Civilization V", ["Civilization VI"] = "Sid Meier's Civilization VI",
        ["Clair Obscur Expedition 33"] = "Clair Obscur: Expedition 33", ["ClusterTruck"] = "Clustertruck",
        ["Corn Kidz 64"] = "Corn Kidz 64", ["CrossCode"] = "CrossCode",
        ["Crypt of the NecroDancer"] = "Crypt of the NecroDancer", ["Crystal Project"] = "Crystal Project",
        ["Crystalis"] = "Crystalis", ["Cuphead"] = "Cuphead", ["DLCQuest"] = "DLC Quest", ["DOOM 1993"] = "DOOM (1993)",
        ["DOOM II"] = "DOOM II", ["DORONKO WANKO"] = "DORONKO WANKO", ["DREDGE"] = "DREDGE",
        ["Dark Cloud 1"] = "Dark Cloud", ["Dark Cloud 2"] = "Dark Cloud 2", ["Dark Souls II"] = "Dark Souls II",
        ["Dark Souls III"] = "Dark Souls III", ["Dark Souls Remastered"] = "Dark Souls: Remastered",
        ["Dead Rising Deluxe Remaster"] = "Dead Rising Deluxe Remaster", ["Death's Door"] = "Death's Door",
        ["Deep Rock Galactic"] = "Deep Rock Galactic", ["Devil May Cry 3"] = "Devil May Cry 3: Dante's Awakening",
        ["Diddy Kong Racing"] = "Diddy Kong Racing", ["Digimon World"] = "Digimon World",
        ["Dome Keeper"] = "Dome Keeper", ["Don't Starve Together"] = "Don't Starve Together",
        ["Donkey Kong 64"] = "Donkey Kong 64", ["Donkey Kong Country 2"] = "Donkey Kong Country 2",
        ["Donkey Kong Country 3"] = "Donkey Kong Country 3", ["Donkey Kong Country"] = "Donkey Kong Country",
        ["Dragon Warrior"] = "Dragon Warrior", ["Duke Nukem 3D"] = "Duke Nukem 3D",
        ["Dungeon Clawler"] = "Dungeon Clawler", ["EarthBound"] = "EarthBound",
        ["Easy Delivery Co."] = "Easy Delivery Co.", ["Ender Lilies"] = "Ender Lilies: Quietus of the Knights",
        ["Enter The Gungeon"] = "Enter the Gungeon", ["FF1 Pixel Remaster"] = "Final Fantasy [Pixel Remaster]",
        ["FFPS"] = "Freddy Fazbear's Pizzeria Simulator", ["FNaFW"] = "FNaF World", ["Factorio"] = "Factorio",
        ["Faxanadu"] = "Faxanadu", ["Fez"] = "Fez", ["Final Fantasy 12 Open World"] = "Final Fantasy XII",
        ["Final Fantasy 6 Worlds Collide"] = "Final Fantasy VI",
        ["Final Fantasy IV Free Enterprise"] = "Final Fantasy IV",
        ["Final Fantasy Mystic Quest"] = "Final Fantasy: Mystic Quest",
        ["Final Fantasy Tactics A2"] = "Final Fantasy Tactics A2",
        ["Final Fantasy Tactics Advance"] = "Final Fantasy Tactics Advance",
        ["Final Fantasy XII Trial Mode"] = "Final Fantasy XII", ["Final Fantasy XIV"] = "Final Fantasy XIV",
        ["Final Fantasy"] = "Final Fantasy", ["Fire Emblem Sacred Stones"] = "Fire Emblem: The Sacred Stones",
        ["Frogmonster"] = "Frogmonster", ["Garfield Kart - Furious Racing"] = "Garfield Kart: Furious Racing",
        ["Gauntlet Legends"] = "Gauntlet Legends", ["Getting Over It"] = "Getting Over It with Bennett Foddy",
        ["Glover"] = "Glover", ["Golden Sun The Lost Age"] = "Golden Sun: The Lost Age", ["Grim Dawn"] = "Grim Dawn",
        ["Guild Wars 2"] = "Guild Wars 2", ["HITMAN World of Assassination"] = "HITMAN World of Assassination",
        ["Hades"] = "Hades", ["Hammerwatch"] = "Hammerwatch", ["Haste"] = "HASTE",
        ["Hatsune Miku Project Diva Mega Mix+"] = "Hatsune Miku: Project Diva Mega Mix+",
        ["Here Comes Niko!"] = "Here Comes Niko!", ["Heretic"] = "Heretic", ["Hi-Fi RUSH"] = "Hi-Fi RUSH",
        ["Hollow Knight"] = "Hollow Knight", ["Hylics 2"] = "Hylics 2", ["Inscryption"] = "Inscryption",
        ["Into the Breach"] = "Into the Breach", ["Isles Of Sea And Sky"] = "Isles Of Sea And Sky",
        ["Ittle Dew 2"] = "Ittle Dew 2+",
        ["Jak and Daxter The Precursor Legacy"] = "Jak and Daxter: The Precursor Legacy",
        ["Keep Talking and Nobody Explodes"] = "Keep Talking and Nobody Explodes", ["KeyWe"] = "KeyWe",
        ["Kindergarten 2"] = "Kindergarten 2", ["Kingdom Hearts 2"] = "KINGDOM HEARTS II FINAL MIX",
        ["Kingdom Hearts Birth by Sleep"] = "KINGDOM HEARTS Birth by Sleep",
        ["Kingdom Hearts RE Chain of Memories"] = "KINGDOM HEARTS Re:Chain of Memories",
        ["Kingdom Hearts"] = "KINGDOM HEARTS FINAL MIX",
        ["Kirby 64 - The Crystal Shards"] = "Kirby 64: The Crystal Shards", ["Kirby Air Ride"] = "Kirby Air Ride",
        ["Kirby Super Star"] = "Kirby Super Star", ["Kirby's Dream Land 3"] = "Kirby's Dream Land 3",
        ["Landstalker - The Treasures of King Nole"] = "Landstalker - The Treasures of King Nole",
        ["League of Legends"] = "League of Legends", ["Left 4 Dead 2"] = "Left 4 Dead 2",
        ["Lego Batman: The Video Game"] = "LEGO Batman: The Video Game",
        ["Lego Star Wars: The Complete Saga"] = "LEGO Star Wars: The Complete Saga",
        ["Lethal Company"] = "Lethal Company", ["Lies Of P"] = "Lies of P",
        ["Lightning Returns: Final Fantasy XIII"] = "Lightning Returns: Final Fantasy XIII",
        ["Lil Gator Game"] = "Lil Gator Game", ["Lingo 2"] = "Lingo 2", ["Lingo"] = "Lingo",
        ["Links Awakening DX Beta"] = "The Legend of Zelda: Link's Awakening DX",
        ["Links Awakening DX"] = "The Legend of Zelda: Link's Awakening DX",
        ["Lufia II Ancient Cave"] = "Lufia II: Rise of the Sinistrals", ["Luigi's Mansion"] = "Luigi's Mansion",
        ["Lunacid"] = "Lunacid", ["Majora's Mask Recompiled"] = "The Legend of Zelda: Majora's Mask",
        ["Mario & Luigi Superstar Saga"] = "Mario & Luigi: Superstar Saga", ["Mario Kart 64"] = "Mario Kart 64",
        ["Mario Kart Double Dash"] = "Mario Kart Double Dash!!", ["Medievil 2"] = "MediEvil II",
        ["Medievil"] = "MediEvil", ["Mega Man 2"] = "Mega Man 2", ["Mega Man 3"] = "Mega Man 3",
        ["Mega Man X Command Mission"] = "Mega Man X: Command Mission", ["Mega Man X"] = "Mega Man X",
        ["Mega Man X2"] = "Mega Man X2", ["Mega Man X3"] = "Mega Man X3", ["Mega Man Zero 3"] = "Mega Man Zero 3",
        ["MegaMan Battle Network 3"] = "Mega Man Battle Network 3",
        ["MegaMan Battle Network 6"] = "Mega Man Battle Network 6", ["MetroCUBEvania"] = "MetroCUBEvania",
        ["Metroid Fusion"] = "Metroid Fusion", ["Metroid Prime"] = "Metroid Prime",
        ["Metroid Zero Mission"] = "Metroid: Zero Mission", ["Mindustry"] = "Mindustry",
        ["Minecraft Dig"] = "Minecraft", ["Minecraft"] = "Minecraft",
        ["Minishoot Adventures"] = "Minishoot' Adventures", ["Minit"] = "Minit",
        ["Momodora 4 - Reverie Under the Moonlight"] = "Momodora: Reverie Under the Moonlight",
        ["Momodora Moonlit Farewell"] = "Momodora: Moonlit Farewell",
        ["Monster Hunter World"] = "Monster Hunter: World", ["Monster Sanctuary"] = "Monster Sanctuary",
        ["Muse Dash"] = "Muse Dash", ["Nine Sols"] = "Nine Sols", ["Nodebuster"] = "Nodebuster", ["Noita"] = "Noita",
        ["Oblivion Remastered"] = "The Elder Scrolls IV: Oblivion Remastered",
        ["Ocarina of Time"] = "The Legend of Zelda: Ocarina of Time", ["Old School Runescape"] = "Old School RuneScape",
        ["OpenRCT2"] = "OpenRCT2", ["Ori and the Blind Forest"] = "Ori and the Blind Forest",
        ["Ori and the Will of the Wisps"] = "Ori and the Will of the Wisps", ["Outer Wilds"] = "Outer Wilds",
        ["Overcooked! 2"] = "Overcooked! 2", ["Oxygen Not Included"] = "Oxygen Not Included", ["PEAK"] = "PEAK",
        ["Paper Mario"] = "Paper Mario",
        ["Paper Mario: The Thousand-Year Door"] = "Paper Mario: The Thousand-Year Door", ["Parkitect"] = "Parkitect",
        ["Path of Exile"] = "Path of Exile", ["Peaks of Yore"] = "Peaks of Yore", ["Pikmin 2"] = "Pikmin 2",
        ["Pikmin"] = "Pikmin", ["Pizza Tower"] = "Pizza Tower",
        ["Plants vs. Zombies Replanted"] = "Plants vs. Zombies: Replanted",
        ["Pokemon Black and White"] = "Pokémon Black and White", ["Pokemon Crystal"] = "Pokémon Crystal",
        ["Pokemon Emerald"] = "Pokémon Emerald", ["Pokemon FireRed and LeafGreen"] = "Pokémon FireRed and LeafGreen",
        ["Pokemon Mystery Dungeon Explorers of Sky"] = "Pokémon Mystery Dungeon: Explorers of Sky",
        ["Pokemon Platinum"] = "Pokémon Platinum", ["Pokemon Red and Blue"] = "Pokémon Red and Blue",
        ["Pokemon Stadium"] = "Pokémon Stadium", ["Portal 2"] = "Portal 2",
        ["Powerwash Simulator"] = "PowerWash Simulator", ["Prodigal"] = "Prodigal", ["Pseudoregalia"] = "Pseudoregalia",
        ["Psychonauts"] = "Psychonauts", ["Quake 1"] = "Quake", ["Rabi-Ribi"] = "Rabi-Ribi", ["Raft"] = "Raft",
        ["Rain World"] = "Rain World", ["Ratchet & Clank 2"] = "Ratchet & Clank: Going Commando",
        ["Ratchet & Clank 3"] = "Ratchet & Clank: Up Your Arsenal", ["Ratchet & Clank"] = "Ratchet & Clank",
        ["Resident Evil 2 Remake"] = "Resident Evil 2 (Remake)",
        ["Resident Evil 3 Remake"] = "Resident Evil 3 (Remake)", ["Reventure"] = "Reventure",
        ["Rift Wizard"] = "Rift Wizard", ["Rift of the Necrodancer"] = "Rift of the NecroDancer",
        ["Rimworld"] = "RimWorld", ["Risk of Rain 2"] = "Risk of Rain 2", ["Risk of Rain"] = "Risk of Rain",
        ["Rogue Legacy"] = "Rogue Legacy", ["Rusted Moss"] = "Rusted Moss",
        ["SMW: Spicy Mycena Waffles"] = "Super Mario World [Waffles]", ["Satisfactory"] = "Satisfactory",
        ["Scooby-Doo! Night of 100 Frights"] = "Scooby-Doo! Night of 100 Frights",
        ["Sea of Thieves"] = "Sea of Thieves", ["Secret of Evermore"] = "Secret of Evermore",
        ["Sentinels of the Multiverse"] = "Sentinels of the Multiverse",
        ["Shadow The Hedgehog"] = "Shadow the Hedgehog",
        ["Ship of Harkinian"] = "The Legend of Zelda: Ocarina of Time [Ship of Harkinian]", ["Shivers"] = "Shivers",
        ["Shovel Knight Pocket Dungeon"] = "Shovel Knight: Pocket Dungeon", ["Signalis"] = "SIGNALIS",
        ["Skyward Sword"] = "The Legend of Zelda: Skyward Sword", ["Slay the Spire"] = "Slay the Spire",
        ["Slime Rancher"] = "Slime Rancher", ["Sly 2: Band of Thieves"] = "Sly 2: Band of Thieves",
        ["Sly Cooper and the Thievius Raccoonus"] = "Sly Cooper and the Thievius Raccoonus",
        ["Smushi Come Home"] = "Smushi Come Home", ["Sonic Advance 2"] = "Sonic Advance 2",
        ["Sonic Adventure 2 Battle"] = "Sonic Adventure 2: Battle", ["Sonic Adventure DX"] = "Sonic Adventure DX",
        ["Sonic Battle"] = "Sonic Battle", ["Sonic Heroes"] = "Sonic Heroes", ["Sonic Riders"] = "Sonic Riders",
        ["Sonic Rush"] = "Sonic Rush", ["Sonic the Hedgehog 1"] = "Sonic the Hedgehog", ["Soul Blazer"] = "Soul Blazer",
        ["Spelunker"] = "Spelunker", ["Spelunky 2"] = "Spelunky 2", ["Spyro 2"] = "Spyro 2: Ripto's Rage!",
        ["Spyro 3"] = "Spyro: Year of the Dragon", ["Spyro the Dragon"] = "Spyro the Dragon",
        ["Stacklands"] = "Stacklands", ["Star Fox 64"] = "Star Fox 64",
        ["Star Wars Episode I Racer"] = "Star Wars: Episode I - Racer", ["Starcraft 2"] = "StarCraft II",
        ["Stardew Valley"] = "Stardew Valley", ["Subnautica"] = "Subnautica",
        ["Subversion"] = "Super Metroid: Subversion", ["Super Cat Planet"] = "Super Cat Planet",
        ["Super Junkoid"] = "Super Junkoid", ["Super Mario 64"] = "Super Mario 64",
        ["Super Mario Land 2"] = "Super Mario Land 2: 6 Golden Coins",
        ["Super Mario RPG Legend of the Seven Stars"] = "Super Mario RPG: Legend of the Seven Stars",
        ["Super Mario Sunshine"] = "Super Mario Sunshine", ["Super Mario World"] = "Super Mario World",
        ["Super Metroid Map Rando"] = "Super Metroid", ["Super Metroid"] = "Super Metroid",
        ["Super Smash Bros. Melee"] = "Super Smash Bros. Melee", ["Supraland"] = "Supraland",
        ["Symphony of the Night"] = "Castlevania: Symphony of the Night", ["System Shock 2"] = "System Shock 2",
        ["TCG Card Shop Simulator"] = "TCG Card Shop Simulator", ["TOEM A Photo Adventure"] = "TOEM",
        ["TUNIC"] = "TUNIC", ["Terraria"] = "Terraria", ["Tetris Attack"] = "Tetris Attack", ["Tevi"] = "TEVI",
        ["The Binding of Isaac Repentance"] = "The Binding of Isaac: Repentance",
        ["The Guardian Legend"] = "The Guardian Legend",
        ["The Legend of Zelda - Oracle of Ages"] = "The Legend of Zelda: Oracle of Ages",
        ["The Legend of Zelda - Oracle of Seasons"] = "The Legend of Zelda: Oracle of Seasons",
        ["The Legend of Zelda - Phantom Hourglass"] = "The Legend of Zelda: Phantom Hourglass",
        ["The Legend of Zelda - Spirit Tracks"] = "The Legend of Zelda: Spirit Tracks",
        ["The Legend of Zelda"] = "The Legend of Zelda", ["The Messenger"] = "The Messenger",
        ["The Minish Cap"] = "The Legend of Zelda: The Minish Cap",
        ["The Simpsons Hit And Run"] = "The Simpsons: Hit & Run", ["The Sims 4"] = "The Sims 4",
        ["The Wind Waker"] = "The Legend of Zelda: The Wind Waker", ["The Witness"] = "The Witness",
        ["Timespinner"] = "Timespinner", ["ToeJam and Earl"] = "ToeJam & Earl",
        ["Total War Warhammer 3"] = "Total War: WARHAMMER III",
        ["Totally Accurate Battle Simulator"] = "Totally Accurate Battle Simulator",
        ["Touhou 6"] = "Touhou 6: Embodiment of Scarlet Devil", ["Trackmania"] = "Trackmania",
        ["Trails in the Sky the 3rd"] = "The Legend of Heroes: Trails in the Sky the 3rd",
        ["TurnipBoy"] = "Turnip Boy Commits Tax Evasion",
        ["Twilight Princess"] = "The Legend of Zelda: Twilight Princess",
        ["Ty the Tasmanian Tiger 2"] = "TY the Tasmanian Tiger 2: Bush Rescue",
        ["Ty the Tasmanian Tiger 3"] = "TY the Tasmanian Tiger 3: Night of the Quinkan",
        ["Ty the Tasmanian Tiger"] = "Ty the Tasmanian Tiger", ["Tyrian"] = "Tyrian", ["UFO 50"] = "UFO 50",
        ["ULTRAKILL"] = "ULTRAKILL", ["Undertale"] = "Undertale", ["Unfair Flips"] = "Unfair Flips",
        ["VVVVVV"] = "VVVVVV", ["Valheim"] = "Valheim", ["Vampire Survivors"] = "Vampire Survivors",
        ["Void Stranger"] = "Void Stranger", ["WEBFISHING"] = "WEBFISHING", ["Wargroove 2"] = "Wargroove 2",
        ["Wargroove"] = "Wargroove", ["Wario Land 4"] = "Wario Land 4",
        ["Wario Land"] = "Wario Land: Super Mario Land 3", ["West of Loathing"] = "West of Loathing",
        ["XCOM 2 War of the Chosen"] = "XCOM 2: War of the Chosen", ["Xenoblade X"] = "Xenoblade Chronicles X",
        ["Yoku's Island Express"] = "Yoku's Island Express", ["Yooka-Laylee"] = "Yooka-Laylee",
        ["Yoshi's Island"] = "Super Mario World 2: Yoshi's Island",
        ["Yu-Gi-Oh! 2006"] = "Yu-Gi-Oh! Ultimate Masters: WCT 2006",
        ["Yu-Gi-Oh! Dungeon Dice Monsters"] = "Yu-Gi-Oh! Dungeon Dice Monsters",
        ["Yu-Gi-Oh! Forbidden Memories"] = "Yu-Gi-Oh! Forbidden Memories",
        ["Yu-Gi-Oh! GX: Duel Academy"] = "Yu-Gi-Oh! GX: Duel Academy",
        ["Zelda II: The Adventure of Link"] = "Zelda II: The Adventure of Link", ["Zillion"] = "Zillion",
        ["Zork Grand Inquisitor"] = "Zork: Grand Inquisitor", ["osu!"] = "Osu!", ["plateup"] = "PlateUp!",
        ["shapez 2"] = "Shapez 2", ["shapez"] = "Shapez",
    };
}