using Godot.Collections;

namespace HydraTextClient.Scripts.Discord;

public static class DRPC_GTI
{
    public static Dictionary<string, string> GameToImage = new()
    {
        ["A Hat in Time"] = "ahatintime", ["A Link Between Worlds"] = "thelegendofzeldaalinkbetweenworlds",
        ["A Link to the Past"] = "thelegendofzeldaalinktothepast", ["A Short Hike"] = "ashorthike",
        ["ANIMAL WELL"] = "animalwell", ["Adventure"] = "adventure", ["Against the Storm"] = "againstthestorm",
        ["Anodyne"] = "anodyne", ["Another Crabs Treasure"] = "anothercrabstreasure", ["Ape Escape 3"] = "apeescape3",
        ["Ape Escape"] = "apeescape", ["Aquaria"] = "aquaria", ["Astalon"] = "astalon", ["Balatro"] = "balatro",
        ["Baldur's Gate 3"] = "baldursgate3", ["Banjo-Tooie"] = "banjotooie",
        ["Battle for Bikini Bottom"] = "spongebobsquarepantsbattleforbikinibottom", ["Blasphemous 2"] = "blasphemous2",
        ["Blasphemous"] = "blasphemous", ["Bomb Rush Cyberfunk"] = "bombrushcyberfunk",
        ["Bomberman 64"] = "bomberman64", ["Bomberman Hero"] = "bombermanhero", ["Bomberman Quest"] = "bombermanquest",
        ["Bomberman The Second Attack"] = "bomberman64thesecondattack", ["Borderlands 2"] = "borderlands2",
        ["Brotato"] = "brotato", ["Buckshot Roulette"] = "buckshotroulette", ["Cassette Beasts"] = "cassettebeasts",
        ["Castlevania - Circle of the Moon"] = "castlevaniacircleofthemoon",
        ["Castlevania - Harmony of Dissonance"] = "castlevaniaharmonyofdissonance",
        ["Castlevania 64"] = "castlevania64", ["Castlevania: Dawn of Sorrow"] = "castlevaniadawnofsorrow",
        ["Celeste (Open World)"] = "celeste", ["Celeste 64"] = "celeste64", ["Celeste"] = "celeste",
        ["Choo-Choo Charles"] = "choochoocharles", ["Chrono Trigger Jets of Time"] = "chronotrigger",
        ["Civilization V"] = "sidmeierscivilizationv", ["Civilization VI"] = "sidmeierscivilizationvi",
        ["Clair Obscur Expedition 33"] = "clairobscurexpedition33", ["CrossCode"] = "crosscode",
        ["Crypt of the NecroDancer"] = "cryptofthenecrodancer", ["Crystal Project"] = "crystalproject",
        ["Crystalis"] = "crystalis", ["Cuphead"] = "cuphead", ["DLCQuest"] = "dlcquest", ["DOOM 1993"] = "doom1993",
        ["DOOM II"] = "doom2", ["DREDGE"] = "dredge", ["Dark Cloud 1"] = "darkcloud", ["Dark Cloud 2"] = "darkcloud2",
        ["Dark Souls II"] = "darksouls2", ["Dark Souls III"] = "darksouls3",
        ["Dark Souls Remastered"] = "darksoulsremastered", ["Dead Rising Deluxe Remaster"] = "deadrisingdeluxeremaster",
        ["Death's Door"] = "deathsdoor", ["Deep Rock Galactic"] = "deeprockgalactic",
        ["Devil May Cry 3"] = "devilmaycry3dantesawakening", ["Diddy Kong Racing"] = "diddykongracing",
        ["Dome Keeper"] = "domekeeper", ["Don't Starve Together"] = "dontstarvetogether",
        ["Donkey Kong 64"] = "donkeykong64", ["Donkey Kong Country 2"] = "donkeykongcountry2",
        ["Donkey Kong Country 3"] = "donkeykongcountry3", ["Donkey Kong Country"] = "donkeykongcountry",
        ["Dragon Warrior"] = "dragonwarrior", ["Duke Nukem 3D"] = "dukenukem3d", ["EarthBound"] = "earthbound",
        ["Easy Delivery Co."] = "easydeliveryco", ["Ender Lilies"] = "enderlilies",
        ["Enter The Gungeon"] = "enterthegungeon", ["FF1 Pixel Remaster"] = "finalfantasypixelremaster",
        ["Factorio"] = "factorio", ["Faxanadu"] = "faxanadu", ["Fez"] = "fez",
        ["Final Fantasy 12 Open World"] = "finalfantasy12", ["Final Fantasy 6 Worlds Collide"] = "finalfantasy6",
        ["Final Fantasy IV Free Enterprise"] = "finalfantasy4",
        ["Final Fantasy Mystic Quest"] = "finalfantasymysticquest",
        ["Final Fantasy Tactics A2"] = "finalfantasytacticsa2",
        ["Final Fantasy Tactics Advance"] = "finalfantasytacticsadvance",
        ["Final Fantasy XII Trial Mode"] = "finalfantasy12", ["Final Fantasy XIV"] = "finalfantasy14",
        ["Final Fantasy"] = "finalfantasy", ["Fire Emblem Sacred Stones"] = "fireemblemthesacredstones",
        ["Frogmonster"] = "frogmonster", ["Garfield Kart - Furious Racing"] = "garfieldkartfuriousracing",
        ["Glover"] = "glover", ["Golden Sun The Lost Age"] = "goldensunthelostage", ["Grim Dawn"] = "grimdawn",
        ["HITMAN World of Assassination"] = "hitmanworldofassassination", ["Hades"] = "hades", ["Haste"] = "haste",
        ["Hatsune Miku Project Diva Mega Mix+"] = "hatsunemikuprojectdivamegamix", ["Heretic"] = "heretic",
        ["Hi-Fi RUSH"] = "hifirush", ["Hollow Knight"] = "hollowknight", ["Hylics 2"] = "hylics2",
        ["Inscryption"] = "inscryption", ["Into the Breach"] = "intothebreach",
        ["Isles Of Sea And Sky"] = "islesofseaandsky", ["Ittle Dew 2"] = "ittledew2",
        ["Jak and Daxter The Precursor Legacy"] = "jakanddaxtertheprecursorlegacy",
        ["Keep Talking and Nobody Explodes"] = "keeptalkingandnobodyexplodes", ["KeyWe"] = "keywe",
        ["Kingdom Hearts 2"] = "kingdomhearts2finalmix",
        ["Kingdom Hearts Birth by Sleep"] = "kingdomheartsbirthbysleep",
        ["Kingdom Hearts RE Chain of Memories"] = "kingdomheartsrechainofmemories",
        ["Kingdom Hearts"] = "kingdomheartsfinalmix", ["Kirby 64 - The Crystal Shards"] = "kirby64thecrystalshards",
        ["Kirby Air Ride"] = "kirbyairride", ["Kirby Super Star"] = "kirbysuperstar",
        ["Kirby's Dream Land 3"] = "kirbysdreamland3",
        ["Landstalker - The Treasures of King Nole"] = "landstalkerthetreasuresofkingnole",
        ["Left 4 Dead 2"] = "left4dead2", ["Lego Batman: The Video Game"] = "legobatmanthevideogame",
        ["Lego Star Wars: The Complete Saga"] = "legostarwarsthecompletesaga", ["Lethal Company"] = "lethalcompany",
        ["Lies Of P"] = "liesofp", ["Lightning Returns: Final Fantasy XIII"] = "lightningreturnsfinalfantasy13",
        ["Lingo 2"] = "lingo2", ["Lingo"] = "lingo", ["Links Awakening DX Beta"] = "thelegendofzeldalinksawakeningdx",
        ["Links Awakening DX"] = "thelegendofzeldalinksawakeningdx",
        ["Lufia II Ancient Cave"] = "lufiaiiriseofthesinistrals", ["Luigi's Mansion"] = "luigismansion",
        ["Lunacid"] = "lunacid", ["Majora's Mask Recompiled"] = "thelegendofzeldamajorasmask",
        ["Mario & Luigi Superstar Saga"] = "marioluigisuperstarsaga", ["Mario Kart 64"] = "mariokart64",
        ["Mario Kart Double Dash"] = "mariokartdoubledash", ["Medievil 2"] = "medievil2", ["Medievil"] = "medievil",
        ["Mega Man 2"] = "megaman2", ["Mega Man 3"] = "megaman3",
        ["Mega Man X Command Mission"] = "megamanxcommandmission", ["Mega Man X"] = "megamanx",
        ["Mega Man X2"] = "megamanx2", ["Mega Man X3"] = "megamanx3", ["Mega Man Zero 3"] = "megamanzero3",
        ["MegaMan Battle Network 3"] = "megamanbattlenetwork3", ["MegaMan Battle Network 6"] = "megamanbattlenetwork6",
        ["Metroid Fusion"] = "metroidfusion", ["Metroid Prime"] = "metroidprime",
        ["Metroid Zero Mission"] = "metroidzeromission", ["Minecraft Dig"] = "minecraft", ["Minecraft"] = "minecraft",
        ["Minishoot Adventures"] = "minishootadventures",
        ["Momodora 4 - Reverie Under the Moonlight"] = "momodorareverieunderthemoonlight",
        ["Momodora Moonlit Farewell"] = "momodoramoonlitfarewell", ["Monster Hunter World"] = "monsterhunterworld",
        ["Monster Sanctuary"] = "monstersanctuary", ["Muse Dash"] = "musedash", ["Nine Sols"] = "ninesols",
        ["Noita"] = "noita", ["Oblivion Remastered"] = "theelderscrolls4oblivionremastered",
        ["Ocarina of Time"] = "thelegendofzeldaocarinaoftime", ["Old School Runescape"] = "oldschoolrunescape",
        ["OpenRCT2"] = "openrct2", ["Ori and the Blind Forest"] = "oriandtheblindforest",
        ["Ori and the Will of the Wisps"] = "oriandthewillofthewisps", ["Outer Wilds"] = "outerwilds",
        ["Overcooked! 2"] = "overcooked2", ["Oxygen Not Included"] = "oxygennotincluded", ["PEAK"] = "peak",
        ["Paper Mario"] = "papermario", ["Paper Mario: The Thousand-Year Door"] = "papermariothethousandyeardoor",
        ["Parkitect"] = "parkitect", ["Path of Exile"] = "pathofexile", ["Pikmin 2"] = "pikmin2", ["Pikmin"] = "pikmin",
        ["Pizza Tower"] = "pizzatower", ["Plants vs. Zombies Replanted"] = "plantsvszombiesreplanted",
        ["Pokemon Black and White"] = "pokemonblackandwhite", ["Pokemon Crystal"] = "pokemoncrystal",
        ["Pokemon Emerald"] = "pokemonemerald", ["Pokemon FireRed and LeafGreen"] = "pokemonfireredandleafgreen",
        ["Pokemon Mystery Dungeon Explorers of Sky"] = "pokemonmysterydungeonexplorersofsky",
        ["Pokemon Platinum"] = "pokemonplatinum", ["Pokemon Red and Blue"] = "pokemonredandblue",
        ["Pokemon Stadium"] = "pokemonstadium", ["Portal 2"] = "portal2",
        ["Powerwash Simulator"] = "powerwashsimulator", ["Pseudoregalia"] = "pseudoregalia",
        ["Psychonauts"] = "psychonauts", ["Quake 1"] = "quake", ["Rabi-Ribi"] = "rabiribi", ["Raft"] = "raft",
        ["Rain World"] = "rainworld", ["Ratchet & Clank 2"] = "ratchetandclankgoingcommando",
        ["Ratchet & Clank 3"] = "ratchetandclankupyourarsenal", ["Ratchet & Clank"] = "ratchetandclank",
        ["Resident Evil 2 Remake"] = "residentevil2remake", ["Resident Evil 3 Remake"] = "residentevil3remake",
        ["Reventure"] = "reventure", ["Rift of the Necrodancer"] = "riftofthenecrodancer", ["Rimworld"] = "rimworld",
        ["Risk of Rain 2"] = "riskofrain2", ["Risk of Rain"] = "riskofrain", ["Rogue Legacy"] = "roguelegacy",
        ["Rusted Moss"] = "rustedmoss", ["SMW: Spicy Mycena Waffles"] = "supermarioworld",
        ["Satisfactory"] = "satisfactory", ["Scooby-Doo! Night of 100 Frights"] = "scoobydoonightof100frights",
        ["Secret of Evermore"] = "secretofevermore", ["Shadow The Hedgehog"] = "shadowthehedgehog",
        ["Ship of Harkinian"] = "thelegendofzeldaocarinaoftime", ["Shivers"] = "shivers",
        ["Shovel Knight Pocket Dungeon"] = "shovelknightpocketdungeon", ["Signalis"] = "signalis",
        ["Skyward Sword"] = "thelegendofzeldaskywardsword", ["Slay the Spire"] = "slaythespire",
        ["Slime Rancher"] = "slimerancher", ["Sly 2: Band of Thieves"] = "sly2bandofthieves",
        ["Sly Cooper and the Thievius Raccoonus"] = "slycooperandthethieviusraccoonus",
        ["Smushi Come Home"] = "smushicomehome", ["Sonic Advance 2"] = "sonicadvance2",
        ["Sonic Adventure 2 Battle"] = "sonicadventure2battle", ["Sonic Adventure DX"] = "sonicadventuredx",
        ["Sonic Battle"] = "sonicbattle", ["Sonic Heroes"] = "sonicheroes", ["Sonic Riders"] = "sonicriders",
        ["Sonic Rush"] = "sonicrush", ["Sonic the Hedgehog 1"] = "sonicthehedgehog", ["Soul Blazer"] = "soulblazer",
        ["Spelunky 2"] = "spelunky2", ["Spyro 2"] = "spyroriptosrage", ["Spyro 3"] = "spyroyearofthedragon",
        ["Spyro the Dragon"] = "spyrothedragon", ["Stacklands"] = "stacklands", ["Star Fox 64"] = "starfox64",
        ["Star Wars Episode I Racer"] = "starwarsepisodeiracer", ["Starcraft 2"] = "starcraft2",
        ["Stardew Valley"] = "stardewvalley", ["Subnautica"] = "subnautica", ["Super Mario 64"] = "supermario64",
        ["Super Mario Land 2"] = "supermarioland26goldencoins",
        ["Super Mario RPG Legend of the Seven Stars"] = "supermariorpglegendofthesevenstars",
        ["Super Mario Sunshine"] = "supermariosunshine", ["Super Mario World"] = "supermarioworld",
        ["Super Metroid Map Rando"] = "supermetroid", ["Super Metroid"] = "supermetroid",
        ["Super Smash Bros. Melee"] = "supersmashbrosmelee", ["Supraland"] = "supraland",
        ["Symphony of the Night"] = "symphonyofthenight", ["System Shock 2"] = "systemshock2",
        ["TCG Card Shop Simulator"] = "tcgcardshopsimulator", ["TOEM A Photo Adventure"] = "toem", ["TUNIC"] = "tunic",
        ["Terraria"] = "terraria", ["Tetris Attack"] = "tetrisattack", ["Tevi"] = "tevi",
        ["The Binding of Isaac Repentance"] = "thebindingofisaacrepentance",
        ["The Guardian Legend"] = "theguardianlegend",
        ["The Legend of Zelda - Oracle of Ages"] = "thelegendofzeldaoracleofages",
        ["The Legend of Zelda - Oracle of Seasons"] = "thelegendofzeldaoracleofseasons",
        ["The Legend of Zelda - Phantom Hourglass"] = "thelegendofzeldaphantomhourglass",
        ["The Legend of Zelda - Spirit Tracks"] = "thelegendofzeldaspirittracks",
        ["The Legend of Zelda"] = "thelegendofzelda", ["The Messenger"] = "themessenger",
        ["The Minish Cap"] = "thelegendofzeldatheminishcap", ["The Simpsons Hit And Run"] = "thesimpsonshitandrun",
        ["The Sims 4"] = "thesims4", ["The Wind Waker"] = "thelegendofzeldathewindwaker",
        ["The Witness"] = "thewitness", ["Timespinner"] = "timespinner",
        ["Total War Warhammer 3"] = "totalwarwarhammer3",
        ["Totally Accurate Battle Simulator"] = "totallyaccuratebattlesimulator", ["Trackmania"] = "trackmania",
        ["Trails in the Sky the 3rd"] = "thelegendofheroestrailsintheskythe3rd",
        ["TurnipBoy"] = "turnipboycommitstaxevasion", ["Twilight Princess"] = "thelegendofzeldatwilightprincess",
        ["Ty the Tasmanian Tiger 2"] = "tythetasmaniantiger2", ["Ty the Tasmanian Tiger 3"] = "tythetasmaniantiger3",
        ["Ty the Tasmanian Tiger"] = "tythetasmaniantiger", ["UFO 50"] = "ufo50", ["ULTRAKILL"] = "ultrakill",
        ["Undertale"] = "undertale", ["Unfair Flips"] = "unfairflips", ["VVVVVV"] = "vvvvvv", ["Valheim"] = "valheim",
        ["Vampire Survivors"] = "vampiresurvivors", ["Void Stranger"] = "voidstranger", ["WEBFISHING"] = "webfishing",
        ["Wargroove 2"] = "wargroove2", ["Wargroove"] = "wargroove", ["Wario Land 4"] = "warioland4",
        ["Wario Land"] = "wariolandsupermarioland3", ["West of Loathing"] = "westofloathing",
        ["XCOM 2 War of the Chosen"] = "xcom2warofthechosen", ["Yoku's Island Express"] = "yokusislandexpress",
        ["Yooka-Laylee"] = "yookalaylee", ["Yoshi's Island"] = "supermarioworld2yoshisisland",
        ["Yu-Gi-Oh! 2006"] = "yugiohultimatemasterswct2006",
        ["Yu-Gi-Oh! Forbidden Memories"] = "yugiohforbiddenmemories",
        ["Zelda II: The Adventure of Link"] = "zelda2theadventureoflink", ["Zillion"] = "zillion",
        ["Zork Grand Inquisitor"] = "zorkgrandinquisitor", ["osu!"] = "osu", ["plateup"] = "plateup",
        ["shapez"] = "shapez",
    };
}